### ISSUE TITLE
Panic concurrent map iteration and map write

### ISSUE THREAD

**Issue by steve-r-west** [elasticpath/epcc-cli#398]
```
WARN[0011] Trying to delete alias related_flow_for_field_slug=field_integer, but it points to id 4b4b897a-c526-4b20-b988-3a9a5b322b99 not 1c4ddfa7-d9d3-4db0-b1d8-a5956a0a354a, this is a bug 
fatal error: concurrent map iteration and map write

goroutine 2309 [running]:
github.com/elasticpath/epcc-cli/external/aliases.GetAliasesForJsonApiTypeAndAlternates({0xc00041d8e4, 0x4}, {0x0, 0x0, 0x0?})
        /home/steveramage/development/epcc/cli/epcc-cli/external/aliases/aliases.go:51 +0x98
github.com/elasticpath/epcc-cli/external/aliases.ResolveAliasValuesOrReturnIdentity({0xc00041d8e4, 0x4}, {0x0, 0x0, 0x0}, {0xc001785530, 0x2a}, {0x17d5b41, 0x2})
        /home/steveramage/development/epcc/cli/epcc-cli/external/aliases/aliases.go:140 +0x175
github.com/elasticpath/epcc-cli/external/json.toJsonObject({0xc002e12400, 0x1e, 0x200?}, 0x0, 0x0, 0x15eac01?, 0x1)
        /home/steveramage/development/epcc/cli/epcc-cli/external/json/to_json.go:100 +0x754
github.com/elasticpath/epcc-cli/external/json.ToJson({0xc002e12400?, 0xc00228b0f0?, 0x10?}, 0x78?, 0xd4?, 0x15582a0?, 0x50?)
        /home/steveramage/development/epcc/cli/epcc-cli/external/json/to_json.go:42 +0x1a5
github.com/elasticpath/epcc-cli/cmd.createInternal({0x1aa7090, 0x26a3ca0}, 0xc000a42000, {0xc00228b0e0, 0x11, 0x12}, 0x1, {0x0, 0x0})
        /home/steveramage/development/epcc/cli/epcc-cli/cmd/create.go:290 +0xcbc

```

**Comment by steve-r-west** [comment]
My guess is this happens if/when concurrent go routines are updating aliases that might be the same.
